# PROD
spring:
  datasource:
    url: jdbc:postgresql://27.71.226.237:9106/tms?ApplicationName=TMS
    # url: jdbc:postgresql://61.28.228.205:15432/tms?ApplicationName=TMS
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    username: "tms_admin"
    password: "123456"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# Hibernate Log levels
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n"
    rolling-file-name: logs/prod-tms-oauth-%d{yyyy-MM-dd}.%i.log
  file:
    name: "logs/prod-tms-oauth.log"
